[package]
authors = ["Florian SAMIEZ <florian.samiez@protonmail.com>"]
edition = "2018"
name = "pong"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.5"
